---
AWSTemplateFormatVersion: 2010-09-09

Description: 'Mirovoy Reference Architecture - Public ALB -
    This template creates a public-facing application load balancer.
    in accordance with the Mirovoy Reference Architecture.'

Metadata:
  Authors:
    Description: Chris Richardson (cwr@mirovoysales.com)

  License:
    Description: 'Copyright 2019 Mirovoy Sales, s.r.o. and its affiliates.
      All Rights Reserved.
      SPDX-License-Identifier: MIT-0'

  History:
    Description: This work is based off of the aws-refarch-wordpress
      templates originally authored by Darryl Osborne (darrylo@amazon.com)

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ALB Parameters
        Parameters:
          - Vpc
          - PublicAlbAcmCertificate
          - PublicAlbSecurityGroup
          - NumberOfSubnets
          - Subnet

    ParameterLabels:
      Vpc:
        default: Vpc Id
      PublicAlbAcmCertificate:
        default: ALB Certificate ARN
      PublicAlbSecurityGroup:
        default: Public ALB Security Group
      NumberOfSubnets:
        default: Number of subnets
      Subnet:
        default: Subnets

Parameters:
  NumberOfSubnets:
    AllowedValues:
      - 2
    Default: 2
    Description: Number of subnets. This must match your selections in the list
      of subnets below.
    Type: String
  PublicAlbAcmCertificate:
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: "[Optional] The AWS Certification Manager certificate ARN
      for the ALB certificate - this certificate should be created in the
      region you wish to run the ALB and must reference the domain
      names you wish to load balance. If you're using phpMyAdmin and www,
      for example, it should include both of those fully qualified
      domains. It is not used for termination of mail TLS connections."
    Description: "[Optional] The AWS Certification Manager certificate ARN
      for the ALB certificate - this certificate should be created in the
      region you wish to run the ALB and must reference the domain
      names you wish to load balance. If you're using phpMyAdmin and www,
      for example, it should include both of those fully qualified
      domains. It is not used for termination of mail TLS connections."
    Type: String
  PublicAlbSecurityGroup:
    Description: Select the ALB security group.
    Type: AWS::EC2::SecurityGroup::Id
  Subnet:
    Description: Select existing subnets. The number selected must match the
      number of subnets above. Subnets selected must be in separate AZs.
    Type: List<AWS::EC2::Subnet::Id>
  Vpc:
    Description: Select an existing Vpc
    Type: AWS::EC2::VPC::Id

Conditions:
  SslCertificate:
    !Not [!Equals ['', !Ref PublicAlbAcmCertificate]]
  NoSslCertificate:
    !Equals ['', !Ref PublicAlbAcmCertificate]
  NumberOfSubnets1:
    !Equals [1, !Ref NumberOfSubnets]
  NumberOfSubnets2:
    !Equals [2, !Ref NumberOfSubnets]
  Subnet0: !Or
    - !Condition NumberOfSubnets1
    - !Condition NumberOfSubnets2
  Subnet1: !Condition NumberOfSubnets2

Resources:
  PublicAlbListenerNoSslCertificate:
    Condition: NoSslCertificate
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PublicAlbTargetGroup
      LoadBalancerArn: !Ref PublicApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  PublicAlbListenerHttpRedirect:
    Condition: SslCertificate
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - PublicApplicationLoadBalancer
    Properties:
      DefaultActions:
        - Order: 100
          RedirectConfig:
            Host: "#{host}"
            Path: "/#{path}"
            Port: 443
            Protocol: "HTTPS"
            Query: "#{query}"
            StatusCode: HTTP_302
          Type: redirect
      LoadBalancerArn: !Ref PublicApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  PublicAlbListenerSslCertificate:
    Condition: SslCertificate
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref PublicAlbAcmCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PublicAlbTargetGroup
      LoadBalancerArn: !Ref PublicApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS

  PublicApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !If
        - NumberOfSubnets1
        - [!Select [0, !Ref Subnet]]
        - [!Select [0, !Ref Subnet], !Select [1, !Ref Subnet]]
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      SecurityGroups:
        - !Ref PublicAlbSecurityGroup
      Tags:
        - Key: Name
          Value: !Join ['', ['Public ALB / ', !Ref 'AWS::StackName']]

  PublicAlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      Port: 443
      Protocol: HTTPS
      Tags:
        - Key: Name
          Value: !Join ['', ['Public ALB / ', !Ref 'AWS::StackName']]
      UnhealthyThresholdCount: 5
      VpcId: !Ref Vpc

Outputs:
  PublicAlbHttpListenerNoSslCertificate:
    Condition: NoSslCertificate
    Value:
      !Ref PublicAlbListenerNoSslCertificate
  PublicAlbHttpsListener:
    Condition: SslCertificate
    Value:
      !Ref PublicAlbListenerSslCertificate
  PublicAlbTargetGroupArn:
    Value:
      !Ref PublicAlbTargetGroup
  PublicAlbCanonicalHostedZoneId:
    Value:
      !GetAtt PublicApplicationLoadBalancer.CanonicalHostedZoneID
  PublicAlbDnsName:
    Value:
      !GetAtt PublicApplicationLoadBalancer.DNSName
  PublicAlbFullName:
    Value:
      !GetAtt PublicApplicationLoadBalancer.LoadBalancerFullName
  PublicAlbHostname:
    Value:
      !If [NoSslCertificate,
           !Join ['',
                  ['http://',
                   !GetAtt PublicApplicationLoadBalancer.DNSName]],
           !Join ['',
                  ['https://',
                   !GetAtt PublicApplicationLoadBalancer.DNSName]]]
  SslCertificate:
    Value:
      !If [SslCertificate, true, false]
